### ISSUE TITLE
Server side rendering integration

### ISSUE THREAD

**Issue by junshengpierre** [bugsnag/bugsnag-react#4]
Hi, does bugsnag-react support SSR? 
I followed the installation instructions but get the error: 
```
Bugsnag Error: "bugsnag-js" is for browser JavaScript only.
  For node, use the "bugsnag" package.
```
when the initial app is rendered on the server with Next.js. If so, how can I integrate it?

Thanks.

**Comment by bengourley** [comment]
Hi @junshengpierre! `bugsnag-js` is specific to browsers so it won't be able to help with things rendered on the server.

For anything that runs on a node server, you will need to integrate [bugsnag (node)](https://github.com/bugsnag/bugsnag-node). From a quick search of next.js's issues, it seems that there isn't a convention on what to do about "universal" error reporting yet… (e.g. https://github.com/zeit/next.js/issues/1852).

In the future we intend to merge the two bugsnag modules such that issues like this don't happen. But until then and with fledgling (albeit great!) ecosystems like that of next.js, things will always be a little rough around the edges until experimentation has made way for convention!

**Comment by junshengpierre** [comment]
Hi @bengourley, thank you for the quick reply. I've managed to successfully integrate bugsnag (node) on the server-side on the project. Alright, I'll experiment and keep a lookout for future updates! Thanks!

**Comment by arild-jacobsen** [comment]
How did you solve it @junshengpierre?

**Comment by dcalhoun** [comment]
@bengourley is support for SSR something your team intends to build for `bugsnag-react` in 2018? There is nothing specific to Next.js (or any other SSR frameworks) preventing this work from being done, correct?

Regardless, would it be worthwhile to reopen this ticket if you do intend to build it eventually?

Thanks!

**Comment by bengourley** [comment]
@dcalhoun we're working on unifying the node/browser notifiers as we speak. See the [universal](https://github.com/bugsnag/bugsnag-js/tree/universal/) branch on bugsnag-js if you want to be nosy!)

Once that is released, SSR support will be possible.

**Comment by BrandonZacharie** [comment]
I agree with @dcalhoun on reopening this ticket

**Comment by BrandonZacharie** [comment]
@bengourley is there a rough ETA for this? I have a deadline in November. If this will be ready (even if only as a prerelease), I will use this then (or now if the API is stable enough).

**Comment by bengourley** [comment]
We should have a prerelease ready by mid september.

**Comment by wbw20** [comment]
thank you for working on this, do you think it will be ready soon? :)

**Comment by bengourley** [comment]
It's almost in an alpha state. The platforms team here has had some other priorities so that estimate has moved a bit. We're at the stage of documentation and internal testing now 🙂

**Comment by concept47** [comment]
Hey @bengourley. Just wanted to do a quick check to see if you had any updates on this, trying to use bugsnag on a next.js/react project and came across this thread.

**Comment by bengourley** [comment]
Hey @concept47, we have a [Next.js example](https://github.com/bugsnag/bugsnag-js/tree/universal/examples/nextjs) ready to go when the universal js notifier is released. We are very close now, should be next week. The example project should give you plenty to go on but the docs won't be live until the release.

**Comment by kbateman** [comment]
in the _error.js in the the next.js example we seem to get some issues from relativeLocation issues (when using page anchors). Would it be better to dynamically require the bugsnagClient if the initialProps has ctx.err rather than always attempt to load it even if not an err ?

**Comment by bengourley** [comment]
@kbateman dynamic require doesn't sound like a good idea to me, I would need to be convinced as to why that would help.

Can you open up a specific issue on [`@bugsnag/js`](https://github.com/bugsnag/bugsnag-js) detailing this problem (steps to reproduce, screenshots, reduced test case if possible). Thanks!
